services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build: ./FoodOrdering.Api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=FoodOrderingDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true"
    depends_on:
      - db
